name: aplikasi_materi_kurikulum
description: Aplikasi Flutter baca materi kurikulum dengan catatan, profil, dan bottom nav.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.2.2
  cached_network_image: ^3.3.0 # âœ… Pastikan ini ada
  font_awesome_flutter: ^10.7.0
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4
  firebase_database: ^12.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
