name: aplikasi_materi_kurikulum
description: Aplikasi Flutter baca materi kurikulum dengan catatan, profil, dan bottom nav.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_database: ^12.0.4
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  font_awesome_flutter: ^10.7.0
  google_mobile_ads: ^7.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  #  WAJIB UNTUK TEST + FIREBASE
  firebase_core_platform_interface: any
  firebase_auth_platform_interface: any
  cloud_firestore_platform_interface: any

flutter:
  uses-material-design: true
